<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductCategory;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get the categories
        $foodsCategory = ProductCategory::where('slug', 'foods')->first();
        $drinksCategory = ProductCategory::where('slug', 'drinks')->first();

        $products = [
            // Food Items
            [
                'name' => 'Fried Rice',
                'description' => 'Delicious fried rice with vegetables and choice of protein',
                'sku' => 'FR-001',
                'barcode' => '1234567890123',
                'price' => 8.99,
                'cost_price' => 4.50,
                'stock_quantity' => 50,
                'min_stock_level' => 10,
                'unit' => 'plate',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $foodsCategory->id,
            ],
            [
                'name' => 'Chicken Burger',
                'description' => 'Juicy grilled chicken breast with lettuce, tomato, and mayo',
                'sku' => 'CB-001',
                'barcode' => '1234567890124',
                'price' => 12.99,
                'cost_price' => 6.50,
                'stock_quantity' => 30,
                'min_stock_level' => 5,
                'unit' => 'piece',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $foodsCategory->id,
            ],
            [
                'name' => 'Caesar Salad',
                'description' => 'Fresh romaine lettuce with parmesan cheese and caesar dressing',
                'sku' => 'CS-001',
                'barcode' => '1234567890125',
                'price' => 9.50,
                'cost_price' => 4.75,
                'stock_quantity' => 25,
                'min_stock_level' => 8,
                'unit' => 'bowl',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $foodsCategory->id,
            ],
            [
                'name' => 'Margherita Pizza',
                'description' => 'Classic pizza with tomato sauce, mozzarella, and fresh basil',
                'sku' => 'MP-001',
                'barcode' => '1234567890126',
                'price' => 15.99,
                'cost_price' => 8.00,
                'stock_quantity' => 20,
                'min_stock_level' => 5,
                'unit' => 'slice',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $foodsCategory->id,
            ],
            [
                'name' => 'Fish & Chips',
                'description' => 'Beer-battered fish with crispy golden fries',
                'sku' => 'FC-001',
                'barcode' => '1234567890127',
                'price' => 13.50,
                'cost_price' => 6.75,
                'stock_quantity' => 35,
                'min_stock_level' => 10,
                'unit' => 'serving',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $foodsCategory->id,
            ],
            [
                'name' => 'Chicken Wings',
                'description' => 'Spicy buffalo wings served with ranch dip',
                'sku' => 'CW-001',
                'barcode' => '1234567890128',
                'price' => 11.99,
                'cost_price' => 5.50,
                'stock_quantity' => 40,
                'min_stock_level' => 12,
                'unit' => 'portion',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $foodsCategory->id,
            ],

            // Beverage Items
            [
                'name' => 'Coffee',
                'description' => 'Freshly brewed coffee made from premium beans',
                'sku' => 'CF-001',
                'barcode' => '1234567890129',
                'price' => 3.50,
                'cost_price' => 1.20,
                'stock_quantity' => 100,
                'min_stock_level' => 20,
                'unit' => 'cup',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $drinksCategory->id,
            ],
            [
                'name' => 'Fresh Orange Juice',
                'description' => '100% pure orange juice freshly squeezed',
                'sku' => 'OJ-001',
                'barcode' => '1234567890130',
                'price' => 4.99,
                'cost_price' => 2.00,
                'stock_quantity' => 60,
                'min_stock_level' => 15,
                'unit' => 'glass',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $drinksCategory->id,
            ],
            [
                'name' => 'Green Tea',
                'description' => 'Premium green tea with antioxidants',
                'sku' => 'GT-001',
                'barcode' => '1234567890131',
                'price' => 2.99,
                'cost_price' => 0.80,
                'stock_quantity' => 80,
                'min_stock_level' => 20,
                'unit' => 'cup',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $drinksCategory->id,
            ],
            [
                'name' => 'Coca Cola',
                'description' => 'Classic Coca Cola soft drink',
                'sku' => 'CC-001',
                'barcode' => '1234567890132',
                'price' => 2.50,
                'cost_price' => 1.00,
                'stock_quantity' => 120,
                'min_stock_level' => 30,
                'unit' => 'can',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $drinksCategory->id,
            ],
            [
                'name' => 'Sparkling Water',
                'description' => 'Refreshing sparkling water with lemon',
                'sku' => 'SW-001',
                'barcode' => '1234567890133',
                'price' => 3.25,
                'cost_price' => 1.30,
                'stock_quantity' => 90,
                'min_stock_level' => 25,
                'unit' => 'bottle',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $drinksCategory->id,
            ],
            [
                'name' => 'Hot Chocolate',
                'description' => 'Rich and creamy hot chocolate with marshmallows',
                'sku' => 'HC-001',
                'barcode' => '1234567890134',
                'price' => 4.50,
                'cost_price' => 1.80,
                'stock_quantity' => 0,
                'min_stock_level' => 18,
                'unit' => 'cup',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $drinksCategory->id,
            ],
            [
                'name' => 'Iced Tea',
                'description' => 'Refreshing iced tea with lemon and mint',
                'sku' => 'IT-001',
                'barcode' => '1234567890135',
                'price' => 3.75,
                'cost_price' => 1.50,
                'stock_quantity' => 85,
                'min_stock_level' => 22,
                'unit' => 'glass',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $drinksCategory->id,
            ],
            [
                'name' => 'Smoothie Bowl',
                'description' => 'Acai smoothie bowl topped with granola and fresh fruits',
                'sku' => 'SB-001',
                'barcode' => '1234567890136',
                'price' => 7.99,
                'cost_price' => 3.20,
                'stock_quantity' => 45,
                'min_stock_level' => 12,
                'unit' => 'bowl',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $drinksCategory->id,
            ],

            // Additional Food Items
            [
                'name' => 'Beef Steak',
                'description' => 'Grilled ribeye steak with garlic butter and herbs',
                'sku' => 'BS-001',
                'barcode' => '1234567890137',
                'price' => 24.99,
                'cost_price' => 12.50,
                'stock_quantity' => 0,
                'min_stock_level' => 3,
                'unit' => 'serving',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $foodsCategory->id,
            ],
            [
                'name' => 'Pasta Carbonara',
                'description' => 'Creamy pasta with bacon, eggs, and parmesan cheese',
                'sku' => 'PC-001',
                'barcode' => '1234567890138',
                'price' => 14.50,
                'cost_price' => 7.25,
                'stock_quantity' => 28,
                'min_stock_level' => 8,
                'unit' => 'plate',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $foodsCategory->id,
            ],
            [
                'name' => 'Chicken Tacos',
                'description' => 'Soft shell tacos with seasoned chicken, lettuce, and salsa',
                'sku' => 'CT-001',
                'barcode' => '1234567890139',
                'price' => 10.99,
                'cost_price' => 5.50,
                'stock_quantity' => 32,
                'min_stock_level' => 10,
                'unit' => 'serving',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $foodsCategory->id,
            ],
            [
                'name' => 'Vegetable Stir Fry',
                'description' => 'Fresh mixed vegetables stir-fried with soy sauce and ginger',
                'sku' => 'VS-001',
                'barcode' => '1234567890140',
                'price' => 9.99,
                'cost_price' => 4.50,
                'stock_quantity' => 38,
                'min_stock_level' => 12,
                'unit' => 'plate',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $foodsCategory->id,
            ],
            [
                'name' => 'BBQ Ribs',
                'description' => 'Slow-cooked pork ribs with tangy BBQ sauce',
                'sku' => 'BR-001',
                'barcode' => '1234567890141',
                'price' => 18.99,
                'cost_price' => 9.50,
                'stock_quantity' => 0,
                'min_stock_level' => 6,
                'unit' => 'rack',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $foodsCategory->id,
            ],
            [
                'name' => 'Quinoa Bowl',
                'description' => 'Nutritious quinoa bowl with roasted vegetables and tahini dressing',
                'sku' => 'QB-001',
                'barcode' => '1234567890142',
                'price' => 11.50,
                'cost_price' => 5.75,
                'stock_quantity' => 26,
                'min_stock_level' => 8,
                'unit' => 'bowl',
                'is_active' => true,
                'track_stock' => true,
                'product_category_id' => $foodsCategory->id,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
